<?php

namespace OC\PlatformBundle\Repository;

use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAdvertWithCategories(array $categoryNames)
    {
        $qb = $this->createQueryBuilder('advert');

        $qb->innerJoin('advert.categories', 'category')
           ->addSelect('category');
           
        $qb->where($qb->expr()->in('category.name', $categoryNames));

        return $qb->getQuery()->getResults();
    }

    public function getAdverts($page, $nbPerPage)
    {
        $qb = $this->createQueryBuilder('advert');
                   
        $qb->leftJoin('advert.categories', 'category')
           ->addSelect('category')
           ->leftJoin('advert.image', 'image')
           ->addSelect('image')
           ->orderBy('advert.date', 'DESC')
           ->getQuery();

        $qb->setFirstResult(($page-1) * $nbPerPage)
           ->setMaxResults($nbPerPage);

        return new Paginator($qb, true);
    }
}
